apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  type: NodePort
  selector:
    app: cassandra
  ports:
    - port: 9042
      targetPort: 9042
      nodePort: {{ .Values.cassandra.nodePort }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: {{ .Values.cassandra.image }}
          ports:
            - containerPort: 9042
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: {{ .Values.cassandra.clusterName | quote }}
            - name: CASSANDRA_DC
              value: {{ .Values.cassandra.dc | quote }}
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          volumeMounts:
            - name: data
              mountPath: /var/lib/cassandra
          readinessProbe:
            exec:
              command: ["cqlsh", "-e", "describe cluster"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 20
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.cassandra.storage }}
