apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-worker
spec:
  replicas: {{ .Values.messageWorker.replicas }}
  selector:
    matchLabels:
      app: message-worker
  template:
    metadata:
      labels:
        app: message-worker
    spec:
{{ include "chat.imagePullSecrets" . }}
      containers:
          image: {{ .Values.messageWorker.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy | default "Never" }}
          env:
            - name: KAFKA_BROKERS
              value: {{ include "chat.kafkaBrokers" $ | quote }}
            - name: PG_DSN
              value: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.database }}?sslmode=disable"
            - name: CASS_HOSTS
              value: "cassandra"
            - name: CASS_PORT
              value: "9042"
            - name: CASS_KEYSPACE
              value: "chat"
            - name: REDIS_CACHE_ADDR
              value: "redis-cache:6379"
