apiVersion: apps/v1
kind: Deployment
metadata:
  name: router
spec:
  replicas: {{ .Values.router.replicas }}
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
    spec:
      containers:
        - name: router
          image: {{ .Values.router.image }}
          imagePullPolicy: Never
          env:
            - name: KAFKA_BROKERS
              value: "kafka-1-0.kafka-headless:9092,kafka-2-0.kafka-headless:9092,kafka-3-0.kafka-headless:9092"
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: PG_DSN
              value: "postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@postgres:5432/{{ .Values.postgres.database }}?sslmode=disable"
            - name: GATEWAY_ADDRS
              value: "{{- $grpcPort := .Values.gateway.grpcPort -}}{{- $replicas := int .Values.gateway.replicas -}}{{- range $i := until $replicas -}}{{- if $i }},{{ end -}}gateway-{{ $i }}=gateway-{{ $i }}.gateway:{{ $grpcPort }}{{- end -}}"
